<?php

namespace App\Models;

use function foo\func;
use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;
use App\Notifications\ResetPassword;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    protected $table = 'users';

    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::creating(function ($user) {
            $user->activation_token = str_random(30);
        });
    }

    /**
     * 全球通用头像
     * +-----------------------------------------------------------
     * @functionName : gravatar
     * +-----------------------------------------------------------
     * @param int $size 大小
     * +-----------------------------------------------------------
     * @author yc
     * +-----------------------------------------------------------
     * @return string
     */
    public function gravatar($size = 100)
    {
        $hash = md5(strtolower(trim($this->attributes['email'])));
        return "http://www.gravatar.com/avatar/$hash?s=$size";
    }

    /**
     * 一个用户拥有多条微博
     * +-----------------------------------------------------------
     * @functionName : statuses
     * +-----------------------------------------------------------
     * @author yc
     * +-----------------------------------------------------------
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function statuses()
    {
        return $this->hasMany(Status::class);
    }

    public function sendPasswordResetNotification($token)
    {
        $this->notify(new ResetPassword($token));
    }

    /**
     * 当前用户发布的所有微博
     * +-----------------------------------------------------------
     * @functionName : feed
     * +-----------------------------------------------------------
     * @author yc
     * +-----------------------------------------------------------
     * @return object
     */
    public function feed()
    {
        return $this->statuses()->orderBy('created_at', 'desc');
    }
}
